### ISSUE TITLE
Emscripten and Windows cross compilation is broken

### ISSUE THREAD

**Issue by philsegeler** [antsouchlos/OxygenEngine2#16]
Please fix. Remove `gtest` from anything that is not native linux compilation.

Or use a `.wrap` file, though i don't think this makes sense on `emscripten` anyways.

**Comment by antsouchlos** [comment]
I'm confused. Where are the linux executables added anyways? In `meson.build` I only see the windows ones

**Comment by philsegeler** [comment]
No they are not windows ones. `win_subsystem` is only relevant on windows and ignored anywhere else. But all those `executable(...)` statements run on linux too. I only have a check for `emscripten` because it does not need `sdl2`.

**Comment by antsouchlos** [comment]
Oh, ok! I'll try to have the unit tests run only on native linux compilation then, if possible with a .wrap file in order to not have `googletest` as a dependency

**Comment by philsegeler** [comment]
You don't really need to explicitly declare `gtest` as a subproject though. It can use the system one without it. See how i handle `sdl2`.
