### ISSUE TITLE
OE_SharedIndexMap

### ISSUE THREAD

**Issue by antsouchlos** [antsouchlos/OxygenEngine2#35]
## When checking existence, examine objects names instead of IDs
`include/OE/types/shared_index_map.h`
[line in code](https://github.com/antsouchlos/OxygenEngine2/blob/master/include/OE/types/shared_index_map.h#L209)

## Objects not being flagged as changed

`include/OE/types/shared_index_map.h`
[line in code](https://github.com/antsouchlos/OxygenEngine2/blob/master/include/OE/types/shared_index_map.h#L209)

**Comment by philsegeler** [comment]
This should be fixed now.
