### ISSUE TITLE
Setting a convention for branch names

### ISSUE THREAD

**Issue by antsouchlos** [antsouchlos/OxygenEngine2#5]
You know the drill. I propose something and then we fight.

# Proposed branch name convention

All branches should have a prefix signifying what their purpose is.

## Development branches

These are branches meant for long-term development of some feature (e.g Renderer, Parser, Physics Engine, etc.)
They should be prefixed with `dev/`

## Feature branches

These are branches meant for introducing a feature that doesn't need continuous development (otherwise, use a dev branch).
This could be changing the build system, adding a logger class, etc.
They should be prefixed with `feature/`

## Tidy branches

Tidy branches are meant for tidying everything up: directory structure, code style, filenames, etc.
They should be prefixed with `tidy/`

## Hotfix branches

These are branches meant for quickly fixing a bug that was introduced by some commit.
They should be prefixed with `hotfix/`

## Master branch

Well, the master branch. Nothing should ever be directly changed on here, only on other branches, and then merged with pull requests.

## Overview

```
dev/*     - Continuous development
feature/* - Introduction of some feature
tidy/*    - Tidying up (Code style, naming conventions, ...)
hotfix/*  - Introducing quick fixes for bugs

```

## Do we need a `release` branch?

What I haven't decided yet, is whether it would be advantageous to have a `release` branch, as well as the `master` branch.
The idea being that while the `master` branch should only ever have working and tested features introduced, it is always possible
something may come up when merging two independently developed and tested features.

The `release` branch would then essentially just be a mirror to the well-tested commits on the `master` branch. Every time it is
completely certain that everything works as expected on the `master` branch, it would get merged onto the `release` branch.

**Comment by philsegeler** [comment]
Agree on nearly all of this. A `release` branch is of advantage, but i think too much of a maintenance burden at this point. We might consider this later when the engine has reached a more advanced stage. For now we should consider the master branch to be the working one. This means that whatever is on the master branch should be working 100%. For that do the following:

Before merging with `master` branch, one should first merge the current state of the `master` branch in their own working branch and adapt current changes there, before merging the working branch back to `master` again. This is to avoid the clusterfuck of the situation you had at first trying to merge the new parser, where you had to recommit my previous changes...

**Comment by antsouchlos** [comment]
Agreed: No `release` branch; merge `master` into current branch before merging a pull-request
